### ISSUE TITLE
Set time format to 24h time rather than am/pm

### ISSUE THREAD

**Issue by davish** [davish/obsidian-full-calendar#33]

**Comment by ljantzen** [comment]
Even better: Use Obsidian locale settings for full localized date and time formats, start-of-week (which naturally falls on a monday in Europe) etc.

**Comment by blackpeasy** [comment]
I would prefer manual configuration.

**Comment by davish** [comment]
Fixed in 3cc6a31919b7cd349d1eec177ef96974879b0250.

**Comment by ReaderGuy42** [comment]
Would it be possible to use 24h time in the "new event" window? I have the 24h option turned on, but in the modal window when creating new events I still get AM/PM

**Comment by davish** [comment]
Unfortunately, the built-in time input that Full Calendar uses is based off of browser localization settings. I don't think Obsidian itself exposes this setting.

**Comment by ReaderGuy42** [comment]
OK, that's fine, thanks for the quick reply :)
