### ISSUE TITLE
Recurring event ecery 2 weeks go on the wrong date

### ISSUE THREAD

**Issue by ilcecca** [davish/obsidian-full-calendar#537]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/davish/obsidian-full-calendar/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and didn't find any similar reports.

### Expected Behavior

I have a recurring event that will occur every two weeks on Friday. I've setup this event on a CalDav calendar (infomaniak) and tried to sync through an .ics connection.
All the other events are fine but this one is shown on Saturday and not Friday (starting from the first occurrence).
Can you help me in solving this problem?

### Current behaviour

The event is shown on Saturday instead of Friday

### Steps to reproduce

Create a recurring event that will occur every two weeks

### Calendar information

CalDav calendar from Infomaniak. Share through .ics

### Which Operating Systems are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [X] Android
- [ ] iOS

### Obsidian Version

1.5.3

### Full Calendar Plugin Version

0.10.7

### Checks

- [ ] I have tried it with all other plugins disabled and the error still occurs.

**Comment by ilcecca** [comment]
I've fixed the problem using a 14 days recurring time and it seems to be fine

**Comment by mayplayo** [comment]
i'm facing the same issue with my gcal sync. recurring events go on the next date...does anyone have any solutions?

**Comment by ilcecca** [comment]
Sorry get the notification now 😢  I didn't use gcal so my only suggestion is trying to make a 14 days recurrence of the event. Hope this will help you

**Comment by Aussie-on-Git** [comment]
Still doing it. Recurring event set on Thursday. Appears on Friday. Can't use it like this. :(

**Comment by YouFoundJK** [comment]
This is probably now fixed in this [version](https://github.com/YouFoundJK/plugin-full-calendar/releases/latest), if you are still looking for help.

**Comment by jeffnosis** [comment]
Confirming this is still happening, and not specific to CalDAV/Infomaniak — I'm seeing the identical symptom via a Proton Calendar ICS subscription. A biweekly (every-two-weeks) recurring event, correct on the source calendar (and on Android/web views of the same calendar), consistently displays one day early in Full Calendar — Thursday instead of Friday, from the first occurrence onward. Same bug class as reported here, different ICS provider and different direction of shift, which suggests this is a general RRULE INTERVAL handling issue rather than something specific to one calendar provider's ICS export format.

Re: the suggestion to switch to Full Calendar Remastered — for what it's worth, that fork currently has its own separate unresolved bug (Week/Day time-grid views rendering completely empty after certain cache-invalidating events), so it's not a clean alternative for everyone yet.
